language: node_js
node_js:
  - "8"
  - "10"
  - "12"

cache:
  yarn: true

branches:
  only:
    - master

before_script:
  # ensure we are testing against latest versions of all deps when using Yarn
  - yarn upgrade
